### ISSUE TITLE
train-parallel.py 训练中有错误

### ISSUE THREAD

**Issue by longglecc** [atomicoo/FCH-TTS#11]
Traceback (most recent call last):
  File "/home/gaol/codes/Voices/FCH-TTS/train-parallel.py", line 69, in <module>
    loggers=loggers
  File "/home/gaol/codes/Voices/FCH-TTS/helpers/trainer.py", line 319, in fit
    valid_losses = self._validate(valid_loader)
  File "/home/gaol/codes/Voices/FCH-TTS/helpers/trainer.py", line 419, in _validate
    loss.item(), l1_loss.item(), ssim_loss.item(), drn_loss.item()
AttributeError: 'float' object has no attribute 'item'

**Comment by atomicoo** [comment]
把 .item() 删掉
